using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace WebTrafficInspector.Services
{
    /// <summary>
    /// Generates professional HTML reports for OWASP Top 10 2025 scan results
    /// </summary>
    public class OWASPT10HTMLReportGenerator
    {
        public string GenerateHTMLReport(Dictionary<string, OWASPT10ScanReport> scanResults)
        {
            var html = new StringBuilder();

            html.AppendLine("<!DOCTYPE html>");
            html.AppendLine("<html lang='en'>");
            html.AppendLine("<head>");
            html.AppendLine("    <meta charset='UTF-8'>");
            html.AppendLine("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
            html.AppendLine("    <title>OWASP Top 10 2025 - Security Scan Report</title>");
            html.AppendLine("    <style>");
            html.AppendLine(GetCSS());
            html.AppendLine("    </style>");
            html.AppendLine("</head>");
            html.AppendLine("<body>");

            // Header
            html.AppendLine("<div class='header'>");
            html.AppendLine("    <h1>🛡️ OWASP Top 10 2025 Security Scan Report</h1>");
            html.AppendLine($"    <p>Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
            html.AppendLine($"    <p>Total URLs Scanned: {scanResults.Count}</p>");
            html.AppendLine("</div>");

            // Executive Summary
            html.AppendLine(GenerateExecutiveSummary(scanResults));

            // Vulnerability Summary by Category
            html.AppendLine(GenerateVulnerabilitySummary(scanResults));

            // Detailed Scan Results
            foreach (var scanResult in scanResults)
            {
                html.AppendLine(GenerateDetailedScanResult(scanResult.Key, scanResult.Value));
            }

            // Footer
            html.AppendLine("<div class='footer'>");
            html.AppendLine("    <p>Report generated by Web Traffic Inspector - OWASP Top 10 2025 Scanner</p>");
            html.AppendLine($"    <p>© {DateTime.Now.Year} - All vulnerabilities should be remediated as soon as possible</p>");
            html.AppendLine("</div>");

            html.AppendLine("</body>");
            html.AppendLine("</html>");

            return html.ToString();
        }

        private string GetCSS()
        {
            return @"
                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }

                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    padding: 20px;
                    color: #333;
                    line-height: 1.6;
                }

                .header {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    margin-bottom: 30px;
                    text-align: center;
                }

                .header h1 {
                    color: #667eea;
                    font-size: 32px;
                    margin-bottom: 15px;
                }

                .executive-summary {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    margin-bottom: 30px;
                }

                .executive-summary h2 {
                    color: #667eea;
                    margin-bottom: 20px;
                    border-bottom: 3px solid #667eea;
                    padding-bottom: 10px;
                }

                .stats-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: 20px;
                    margin-top: 20px;
                }

                .stat-card {
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    padding: 20px;
                    border-radius: 10px;
                    text-align: center;
                }

                .stat-card h3 {
                    font-size: 36px;
                    margin-bottom: 10px;
                }

                .stat-card p {
                    font-size: 14px;
                    opacity: 0.9;
                }

                .vulnerability-summary {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    margin-bottom: 30px;
                }

                .vulnerability-summary h2 {
                    color: #667eea;
                    margin-bottom: 20px;
                    border-bottom: 3px solid #667eea;
                    padding-bottom: 10px;
                }

                .category-table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 20px;
                }

                .category-table th,
                .category-table td {
                    padding: 12px;
                    text-align: left;
                    border-bottom: 1px solid #eee;
                }

                .category-table th {
                    background: #667eea;
                    color: white;
                    font-weight: bold;
                }

                .category-table tr:hover {
                    background: #f8f9fa;
                }

                .scan-result {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    margin-bottom: 30px;
                }

                .scan-result h2 {
                    color: #667eea;
                    margin-bottom: 20px;
                    border-bottom: 3px solid #667eea;
                    padding-bottom: 10px;
                    word-break: break-all;
                }

                .scan-info {
                    background: #f8f9fa;
                    padding: 15px;
                    border-radius: 5px;
                    margin-bottom: 20px;
                }

                .scan-info p {
                    margin: 5px 0;
                }

                .vulnerability {
                    background: #fff;
                    border: 2px solid #eee;
                    border-left: 5px solid;
                    border-radius: 5px;
                    padding: 20px;
                    margin: 20px 0;
                }

                .vulnerability.critical {
                    border-left-color: #dc3545;
                    background: #fff5f5;
                }

                .vulnerability.high {
                    border-left-color: #fd7e14;
                    background: #fff8f0;
                }

                .vulnerability.medium {
                    border-left-color: #ffc107;
                    background: #fffef0;
                }

                .vulnerability.low {
                    border-left-color: #28a745;
                    background: #f0fff4;
                }

                .vulnerability h3 {
                    color: #333;
                    margin-bottom: 10px;
                }

                .severity {
                    display: inline-block;
                    padding: 5px 15px;
                    border-radius: 20px;
                    font-weight: bold;
                    font-size: 12px;
                    text-transform: uppercase;
                }

                .severity.critical {
                    background: #dc3545;
                    color: white;
                }

                .severity.high {
                    background: #fd7e14;
                    color: white;
                }

                .severity.medium {
                    background: #ffc107;
                    color: #333;
                }

                .severity.low {
                    background: #28a745;
                    color: white;
                }

                .category-badge {
                    display: inline-block;
                    background: #667eea;
                    color: white;
                    padding: 3px 10px;
                    border-radius: 15px;
                    font-size: 11px;
                    margin-right: 10px;
                }

                .code-block {
                    background: #2d2d2d;
                    color: #f8f8f2;
                    padding: 15px;
                    border-radius: 5px;
                    overflow-x: auto;
                    margin: 10px 0;
                    font-family: 'Courier New', monospace;
                    font-size: 13px;
                }

                .poc-section {
                    background: #f8f9fa;
                    border: 2px solid #667eea;
                    border-radius: 5px;
                    padding: 15px;
                    margin: 15px 0;
                }

                .poc-section h4 {
                    color: #667eea;
                    margin-bottom: 10px;
                }

                .footer {
                    background: white;
                    padding: 20px;
                    border-radius: 10px;
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    text-align: center;
                    margin-top: 30px;
                    color: #666;
                }

                .no-vulnerabilities {
                    background: #d4edda;
                    border: 2px solid #28a745;
                    color: #155724;
                    padding: 20px;
                    border-radius: 10px;
                    text-align: center;
                    margin: 20px 0;
                }

                .no-vulnerabilities h3 {
                    color: #28a745;
                    margin-bottom: 10px;
                }";
        }

        private string GenerateExecutiveSummary(Dictionary<string, OWASPT10ScanReport> scanResults)
        {
            var totalVulnerabilities = scanResults.Values.Sum(r => r.TotalVulnerabilitiesFound);
            var criticalCount = CountVulnerabilitiesBySeverity(scanResults, "Critical");
            var highCount = CountVulnerabilitiesBySeverity(scanResults, "High");
            var mediumCount = CountVulnerabilitiesBySeverity(scanResults, "Medium");
            var lowCount = CountVulnerabilitiesBySeverity(scanResults, "Low");

            var html = new StringBuilder();
            html.AppendLine("<div class='executive-summary'>");
            html.AppendLine("    <h2>📊 Executive Summary</h2>");
            html.AppendLine("    <div class='stats-grid'>");
            html.AppendLine($"        <div class='stat-card'>");
            html.AppendLine($"            <h3>{totalVulnerabilities}</h3>");
            html.AppendLine($"            <p>Total Vulnerabilities</p>");
            html.AppendLine($"        </div>");
            html.AppendLine($"        <div class='stat-card'>");
            html.AppendLine($"            <h3>{criticalCount}</h3>");
            html.AppendLine($"            <p>Critical Issues</p>");
            html.AppendLine($"        </div>");
            html.AppendLine($"        <div class='stat-card'>");
            html.AppendLine($"            <h3>{highCount}</h3>");
            html.AppendLine($"            <p>High Priority</p>");
            html.AppendLine($"        </div>");
            html.AppendLine($"        <div class='stat-card'>");
            html.AppendLine($"            <h3>{mediumCount}</h3>");
            html.AppendLine($"            <p>Medium Priority</p>");
            html.AppendLine($"        </div>");
            html.AppendLine($"        <div class='stat-card'>");
            html.AppendLine($"            <h3>{lowCount}</h3>");
            html.AppendLine($"            <p>Low Priority</p>");
            html.AppendLine($"        </div>");
            html.AppendLine("    </div>");
            html.AppendLine("</div>");

            return html.ToString();
        }

        private string GenerateVulnerabilitySummary(Dictionary<string, OWASPT10ScanReport> scanResults)
        {
            var categoryStats = new Dictionary<string, int>();

            foreach (var scanResult in scanResults.Values)
            {
                foreach (var category in scanResult.VulnerabilitiesByCategory)
                {
                    if (!categoryStats.ContainsKey(category.Key))
                        categoryStats[category.Key] = 0;
                    categoryStats[category.Key] += category.Value.Count;
                }
            }

            var html = new StringBuilder();
            html.AppendLine("<div class='vulnerability-summary'>");
            html.AppendLine("    <h2>🎯 Vulnerability Distribution by OWASP Category</h2>");
            html.AppendLine("    <table class='category-table'>");
            html.AppendLine("        <thead>");
            html.AppendLine("            <tr>");
            html.AppendLine("                <th>OWASP Category</th>");
            html.AppendLine("                <th>Count</th>");
            html.AppendLine("                <th>Risk Level</th>");
            html.AppendLine("            </tr>");
            html.AppendLine("        </thead>");
            html.AppendLine("        <tbody>");

            var owaspCategories = new[]
            {
                "A01:2025 - Broken Access Control",
                "A02:2025 - Security Misconfiguration",
                "A03:2025 - Software Supply Chain Failures",
                "A04:2025 - Cryptographic Failures",
                "A05:2025 - Injection",
                "A06:2025 - Insecure Design",
                "A07:2025 - Authentication Failures",
                "A08:2025 - Software or Data Integrity Failures",
                "A09:2025 - Logging & Alerting Failures",
                "A10:2025 - Mishandling of Exceptional Conditions"
            };

            foreach (var category in owaspCategories)
            {
                var count = categoryStats.ContainsKey(category) ? categoryStats[category] : 0;
                var riskLevel = GetRiskLevel(count);
                var riskColor = GetRiskColor(count);

                html.AppendLine("            <tr>");
                html.AppendLine($"                <td><strong>{HttpUtility.HtmlEncode(category)}</strong></td>");
                html.AppendLine($"                <td><strong>{count}</strong></td>");
                html.AppendLine($"                <td><span class='severity {riskColor.ToLower()}'>{riskLevel}</span></td>");
                html.AppendLine("            </tr>");
            }

            html.AppendLine("        </tbody>");
            html.AppendLine("    </table>");
            html.AppendLine("</div>");

            return html.ToString();
        }

        private string GenerateDetailedScanResult(string url, OWASPT10ScanReport scanReport)
        {
            var html = new StringBuilder();
            html.AppendLine("<div class='scan-result'>");
            html.AppendLine($"    <h2>🌐 {HttpUtility.HtmlEncode(url)}</h2>");

            // Scan Info
            html.AppendLine("    <div class='scan-info'>");
            html.AppendLine($"        <p><strong>Scan Duration:</strong> {scanReport.Duration:F2} seconds</p>");
            html.AppendLine($"        <p><strong>Start Time:</strong> {scanReport.StartTime:yyyy-MM-dd HH:mm:ss}</p>");
            html.AppendLine($"        <p><strong>End Time:</strong> {scanReport.EndTime:yyyy-MM-dd HH:mm:ss}</p>");
            html.AppendLine($"        <p><strong>Total Vulnerabilities Found:</strong> {scanReport.TotalVulnerabilitiesFound}</p>");
            if (!string.IsNullOrEmpty(scanReport.Error))
            {
                html.AppendLine($"        <p style='color: red;'><strong>Error:</strong> {HttpUtility.HtmlEncode(scanReport.Error)}</p>");
            }
            html.AppendLine("    </div>");

            if (scanReport.TotalVulnerabilitiesFound == 0)
            {
                html.AppendLine("    <div class='no-vulnerabilities'>");
                html.AppendLine("        <h3>✅ No Vulnerabilities Detected!</h3>");
                html.AppendLine("        <p>This URL passed all OWASP Top 10 2025 security tests.</p>");
                html.AppendLine("    </div>");
            }
            else
            {
                // Group vulnerabilities by category
                foreach (var category in scanReport.VulnerabilitiesByCategory)
                {
                    if (category.Value.Count > 0)
                    {
                        html.AppendLine($"    <h3 style='color: #667eea; margin-top: 30px;'>{HttpUtility.HtmlEncode(category.Key)}</h3>");

                        foreach (var vuln in category.Value)
                        {
                            html.AppendLine(GenerateVulnerabilityHTML(vuln));
                        }
                    }
                }
            }

            html.AppendLine("</div>");
            return html.ToString();
        }

        private string GenerateVulnerabilityHTML(OWASPT10Vulnerability vuln)
        {
            var severityClass = vuln.Severity.ToLower();

            var html = new StringBuilder();
            html.AppendLine($"    <div class='vulnerability {severityClass}'>");
            html.AppendLine($"        <h3>{HttpUtility.HtmlEncode(vuln.Type)}</h3>");
            html.AppendLine($"        <p><span class='category-badge'>{HttpUtility.HtmlEncode(vuln.Category)}</span>");
            html.AppendLine($"           <span class='severity {severityClass}'>{vuln.Severity}</span></p>");

            html.AppendLine($"        <p><strong>Description:</strong> {HttpUtility.HtmlEncode(vuln.Description)}</p>");

            if (!string.IsNullOrEmpty(vuln.CWE))
            {
                html.AppendLine($"        <p><strong>CWE:</strong> {HttpUtility.HtmlEncode(vuln.CWE)}</p>");
            }

            if (!string.IsNullOrEmpty(vuln.Evidence))
            {
                html.AppendLine($"        <p><strong>Evidence:</strong> {HttpUtility.HtmlEncode(vuln.Evidence)}</p>");
            }

            if (!string.IsNullOrEmpty(vuln.TestUrl))
            {
                html.AppendLine($"        <p><strong>Test URL:</strong></p>");
                html.AppendLine($"        <div class='code-block'>{HttpUtility.HtmlEncode(vuln.TestUrl)}</div>");
            }

            if (!string.IsNullOrEmpty(vuln.TestRequest))
            {
                html.AppendLine($"        <p><strong>Test Request:</strong></p>");
                html.AppendLine($"        <div class='code-block'>{HttpUtility.HtmlEncode(vuln.TestRequest)}</div>");
            }

            if (!string.IsNullOrEmpty(vuln.TestResponse) && vuln.TestResponse.Length < 5000)
            {
                html.AppendLine($"        <p><strong>Test Response (truncated):</strong></p>");
                var truncatedResponse = vuln.TestResponse.Length > 1000
                    ? vuln.TestResponse.Substring(0, 1000) + "..."
                    : vuln.TestResponse;
                html.AppendLine($"        <div class='code-block'>{HttpUtility.HtmlEncode(truncatedResponse)}</div>");
            }

            if (!string.IsNullOrEmpty(vuln.PoC))
            {
                html.AppendLine($"        <div class='poc-section'>");
                html.AppendLine($"            <h4>🔥 Proof of Concept (PoC)</h4>");
                html.AppendLine($"            <pre style='white-space: pre-wrap; word-wrap: break-word;'>{HttpUtility.HtmlEncode(vuln.PoC)}</pre>");
                html.AppendLine($"        </div>");
            }

            html.AppendLine($"    </div>");

            return html.ToString();
        }

        private int CountVulnerabilitiesBySeverity(Dictionary<string, OWASPT10ScanReport> scanResults, string severity)
        {
            return scanResults.Values
                .SelectMany(r => r.VulnerabilitiesByCategory.Values)
                .SelectMany(v => v)
                .Count(v => v.Severity.Equals(severity, StringComparison.OrdinalIgnoreCase));
        }

        private string GetRiskLevel(int count)
        {
            if (count == 0) return "Safe";
            if (count <= 2) return "Low";
            if (count <= 5) return "Medium";
            if (count <= 10) return "High";
            return "Critical";
        }

        private string GetRiskColor(int count)
        {
            if (count == 0) return "low";
            if (count <= 2) return "low";
            if (count <= 5) return "medium";
            if (count <= 10) return "high";
            return "critical";
        }
    }
}
